services:
  - type: web
    name: saedx1-web
    env: static
    staticPublishPath: .
    domains:
      - dev.ps
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
